[tool.black]
line-length = 100
exclude = '''
/(
  \.eggs         # exclude a few common directories in the
| \.git          # root of the project
| \.hg
| .mypy_cache
| .tox
| \.venv
| ve
| dist
)/
'''
